[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

upload_port = COM8
monitor_port = COM8

build_flags =
  -DBOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -DMQTT_MAX_PACKET_SIZE=4096

lib_deps =
  knolleary/PubSubClient@^2.8
