[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.flash_mode = dio
board_upload.flash_size = 2MB
board_build.partitions = partitions.csv
build_flags =
    -DCORE_DEBUG_LEVEL=4
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
lib_deps =
    # Add extra components if needed

[platformio]
default_envs = esp32dev



